name = "RasterHistograms"
uuid = "dfdd8f93-37cf-4dac-b522-93b2288e19f1"
authors = ["Josef Bisits <jbisits@gmail.com>"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Rasters = "a3a2b9e3-a471-40c9-b274-f788e487c689"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
